version: '3.8'

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #     target: dev
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./app/frontend:/app
  #     - /app/node_modules

  # backend:
  #   container_name: backend
  #   build:
  #     context: ./app/backend
  #     dockerfile: Dockerfile
  #     target: dev
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - ./app/backend/:/app
  #     - ./app/backend/node_modules/:/app/node_modules

  # Infrastructure
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: rlwkRQ5%WQ04
    ports:
      - '1433:1433'